baseURL = 'https://agrogur.github.io'
languageCode = 'en-us'
title = 'Uğur Gümüş'
theme = ['hugo-cloak-email', 'digitalgarden']
googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "agrogur's Digital Garden on the Internet"
  images = "/static/ico/favicon.ico"
  enableSearch = true

[Params.newsletter]
  Title= "Monthly round-up"
  Description= "A curated monthly digest delivered to your mailbox once a month."
  provider = "buttondown"
  path = "https://buttondown.email/api/emails/embed-subscribe/agrogur"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5
[[menu.main]]  
  name = 'Jots'
  url = '/jots'
  weight = 6
[[menu.main]]  
  name = 'Verbing'
  url = '/verbing'
  weight = 7  
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 8
[[menu.main]]
  name = 'Blogger'
  url = 'https://argogur.blogspot.com/'
  weight = 9

[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/u47gur'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/agrogur'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/agrogur/'
  weight = 3
[[menu.social]]
  name = 'Instagram'
  url = 'https://instagram.com/agrogur'
  weight = 4
[[menu.social]]
  name = 'Email'
  url = 'mailto:agrogur@gmail.com'
  weight = 5
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 6

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

